In [1]:
import pandas as pd

# Provide the path to your CSV file
csv_file_path = "C:/Users/SATYESH/Downloads/training_data.csv"

# Read the CSV file
df = pd.read_csv(csv_file_path)

# Extract the data from the "job_description" column
job_descriptions = df["job_description"]


In [2]:
def job_description_extractor(path):
    import pandas as pd

    # Provide the path to your CSV file
    csv_file_path = "C:/Users/SATYESH/Downloads/training_data.csv"

    # Read the CSV file
    df = pd.read_csv(csv_file_path)

    # Extract the data from the "job_description" column
    
    job_descriptions = df["job_description"]

    

In [3]:
job_descriptions=job_descriptions[0:10]

In [4]:
job_descriptions

0    minimum qualifications\nbachelors degree or eq...
1    description\nas an asc you will be highly infl...
2    its an amazing time to be joining netflix as w...
3    description\n\nweb designers looking to expand...
4    at trackfive weve got big goals were on a miss...
5    designups is a nashville based design and inte...
6    about the position\n\nthe web designer is resp...
7    job description\n\nzander insurance group is o...
8    tuff is a growth marketing team working with c...
9    type of requisition regular\n\nclearance level...
Name: job_description, dtype: object

In [5]:
job_descriptions

0    minimum qualifications\nbachelors degree or eq...
1    description\nas an asc you will be highly infl...
2    its an amazing time to be joining netflix as w...
3    description\n\nweb designers looking to expand...
4    at trackfive weve got big goals were on a miss...
5    designups is a nashville based design and inte...
6    about the position\n\nthe web designer is resp...
7    job description\n\nzander insurance group is o...
8    tuff is a growth marketing team working with c...
9    type of requisition regular\n\nclearance level...
Name: job_description, dtype: object

In [6]:
type(job_descriptions)

pandas.core.series.Series

In [7]:
#PDF EXTRACTOR

import pdfplumber

# Function to extract text from a PDF file using pdfplumber
def extract_text_from_pdf(pdf_file):
    text = ""
    with pdfplumber.open(pdf_file) as pdf:
        for page in pdf.pages:
            text += page.extract_text()
    return text

# Function to extract education and skills sections
def extract_education(text):
    lines = text.split('\n')
    headers = ["Contact Information","Objective","Summary","Experience","Education","Certifications","Projects","Awards","Achievements","Publications","Languages","Interests","References","Activities","Additional Information"]
    
    education_section = []
    
    in_education_section = False
    flag = False
    
    for line in lines:
        line = line.strip()
        
        if "Education" in line:
            in_education_section = True
            flag = True
        else:
            for header in headers:
                if header in line and flag:
                    in_education_section = False
                    return education_section
        
        if in_education_section and line:
            education_section.append(line)
    
    return education_section

def extract_skills(text):
    lines = text.split('\n')
    headers = ["Contact Information","Objective","Summary","Experience","Education","Certifications","Projects","Awards","Achievements","Publications","Languages","Interests","References","Activities","Additional Information"]
    
    skills_section = []
    
    in_skills_section = False
    flag = False
    
    for line in lines:
        line = line.strip()
        
        if "Skills" in line:
            in_skills_section = True
            flag = True
        else:
            for header in headers:
                if header in line and flag:
                    in_skills_section = False
                    return skills_section
        
        if in_skills_section and line:
            skills_section.append(line)
    
    return skills_section

# Replace 'resume.pdf' with the path to your PDF file
pdf_file = 'C:/Users/SATYESH/Downloads/resumedataset/data/data/ACCOUNTANT/11163645.pdf'

# Extract text from the PDF using pdfplumber
resume_text = extract_text_from_pdf(pdf_file)

# Extract education and skills sections
education = extract_education(resume_text)
skills = extract_skills(resume_text)

# Print the extracted sections
print("Education Section:")
for line in education:
    print(line)

print("\nSkills Section:")
for line in skills:
    print(line)


Education Section:
Education
Computer Applications Specialist Certificate Program : 2008 Martinez Adult Education, Business Training Center ï¼​ City , State
Skills
accounts payables, accounts receivables, Accounts Payable, Accounts Receivable, administrative functions, trial balance, banking, budget, bi,
closing, Computer Applications, Credit, clients, Customer Service, data entry, delivery, driving, email, insurance, inventory, ledger, Access, Excel,
Outlook, PowerPoint, Word, mortgage loan, Enterprise, policies, QuickBooks, Sales, sales reports, telecommunications, phone, workflow,
written

Skills Section:
Skills
accounts payables, accounts receivables, Accounts Payable, Accounts Receivable, administrative functions, trial balance, banking, budget, bi,
closing, Computer Applications, Credit, clients, Customer Service, data entry, delivery, driving, email, insurance, inventory, ledger, Access, Excel,
Outlook, PowerPoint, Word, mortgage loan, Enterprise, policies, QuickBooks, Sales, sa

In [8]:
def cv_details_extractor(path):
    import pdfplumber

    # Function to extract text from a PDF file using pdfplumber
    def extract_text_from_pdf(pdf_file):
        text = ""
        with pdfplumber.open(pdf_file) as pdf:
            for page in pdf.pages:
                text += page.extract_text()
        return text

    # Function to extract education and skills sections
    def extract_education(text):
        lines = text.split('\n')
        headers = ["Contact Information","Objective","Summary","Experience","Skills","Education","Certifications","Projects","Awards","Achievements","Publications","Languages","Interests","References","Activities","Additional Information"]
    
        education_section = []
    
        in_education_section = False
        flag = False
    
        for line in lines:
            line = line.strip()
        
            if "Education" in line:
                in_education_section = True
                flag = True
            else:
                for header in headers:
                    if header in line and flag:
                        in_education_section = False
                        return education_section
        
            if in_education_section and line:
                education_section.append(line)
    
        return education_section

    def extract_skills(text):
        lines = text.split('\n')
        headers = ["Contact Information","Objective","Summary","Experience","Skills","Education","Certifications","Projects","Awards","Achievements","Publications","Languages","Interests","References","Activities","Additional Information"]
    
        skills_section = []
    
        in_skills_section = False
        flag = False
    
        for line in lines:
            line = line.strip()
        
            if "Skills" in line:
                in_skills_section = True
                flag = True
            else:
                for header in headers:
                    if header in line and flag:
                        in_skills_section = False
                        return skills_section
        
            if in_skills_section and line:
                skills_section.append(line)
    
        return skills_section
    
    # Replace 'resume.pdf' with the path to your PDF file
    pdf_file = path

    # Extract text from the PDF using pdfplumber
    resume_text = extract_text_from_pdf(pdf_file)

    # Extract education and skills sections
    education = extract_education(resume_text)
    skills = extract_skills(resume_text)

    # Print the extracted sections
    print("Education Section:")
    for line in education:
        print(line)

    print("\nSkills Section:")
    for line in skills:
        print(line)


In [9]:
#Resume Details extractor of a particular folder and all resumes
import os
import pdfplumber

def cv_details_extractor(pdf_folder_path):
    # Function to extract text from a PDF file using pdfplumber
    def extract_text_from_pdf(pdf_file):
        text = ""
        with pdfplumber.open(pdf_file) as pdf:
            for page in pdf.pages:
                text += page.extract_text()
        return text

    # Function to extract education and skills sections
    def extract_education(text):
        lines = text.split('\n')
        headers = ["Contact Information","Objective","Summary","Experience","Education","Certifications","Projects","Awards","Achievements","Publications","Skills","Languages","Interests","References","Activities","Additional Information"]
    
        education_section = []
    
        in_education_section = False
        flag = False
    
        for line in lines:
            line = line.strip()
        
            if "Education" in line:
                in_education_section = True
                flag = True
            else:
                for header in headers:
                    if header in line and flag:
                        in_education_section = False
                        return education_section
        
            if in_education_section and line:
                education_section.append(line)
    
        return education_section
        # ... (Your existing extract_education function)
        # No need to modify this function

    def extract_skills(text):
        lines = text.split('\n')
        headers = ["Contact Information","Objective","Summary","Experience","Skills","Education","Certifications","Projects","Awards","Achievements","Publications","Languages","Interests","References","Activities","Additional Information"]
    
        skills_section = []
    
        in_skills_section = False
        flag = False
    
        for line in lines:
            line = line.strip()
        
            if "Skills" in line:
                in_skills_section = True
                flag = True
            else:
                for header in headers:
                    if header in line and flag:
                        in_skills_section = False
                        return skills_section
        
            if in_skills_section and line:
                skills_section.append(line)
    
        return skills_section
    
        # ... (Your existing extract_skills function)
        # No need to modify this function

    # Create a dictionary to store results for each resume
    resume_details = {}

    # Iterate through all PDF files in the folder
    for pdf_file in os.listdir(pdf_folder_path):
        if pdf_file.endswith(".pdf"):
            pdf_path = os.path.join(pdf_folder_path, pdf_file)

            # Extract text from the PDF using pdfplumber
            resume_text = extract_text_from_pdf(pdf_path)

            # Extract education and skills sections
            education = extract_education(resume_text)
            skills = extract_skills(resume_text)

            # Store the results in the dictionary using the PDF file name as the key
            resume_details[pdf_file] = {
                "Education Section": education,
                "Skills Section": skills,
            }

    return resume_details

# Define the path to the "ACCOUNTANT" folder
pdf_folder_path = "C:/Users/SATYESH/Downloads/resumedataset/data/data/ENGINEERING"

# Call the function to extract details from all resumes in the folder
all_resume_details = cv_details_extractor(pdf_folder_path)

# Now, all_resume_details is a dictionary where each key is the PDF file name,
# and the corresponding value is a dictionary containing the education and skills sections.
# You can access the details for a specific resume like this:
# education_section = all_resume_details["10554236.pdf"]["Education Section"]
# skills_section = all_resume_details["10554236.pdf"]["Skills Section"]

# You can loop through all_resume_details to access details for all resumes.


In [10]:
    all_resume_details['10030015.pdf']

{'Education Section': ['Education and Training',
  'Associates , Applied Science Electronics Engineering 2011 Forsyth Technical Community College ï¼\u200b City , State Applied Science Electronics',
  'Engineering',
  'Associates , Applied Science, Munitions Systems Technology 2007 Community College of the Air Force ï¼\u200b City , State Applied Science,',
  'Munitions Systems Technology'],
 'Skills Section': ['Skills',
  'DasyLab, Labview, Mechanical, Electrical, Lean/5S, Hydraulic Testing, Test Stand Fabrication']}

In [11]:
cv_details_extractor('C:/Users/SATYESH/Downloads/resumedataset/data/data/ACCOUNTANT/11163645.pdf')

NotADirectoryError: [WinError 267] The directory name is invalid: 'C:/Users/SATYESH/Downloads/resumedataset/data/data/ACCOUNTANT/11163645.pdf'

In [12]:
#Resume details extractor of all folders and all resumes
import os
import pdfplumber

def cv_details_extractor(parent_folder_path):
    # Function to extract text from a PDF file using pdfplumber
    def extract_text_from_pdf(pdf_file):
        text = ""
        with pdfplumber.open(pdf_file) as pdf:
            for page in pdf.pages:
                text += page.extract_text()
        return text

    # Function to extract education and skills sections
    def extract_education(text):
        lines = text.split('\n')
        headers = ["Contact Information","Objective","Summary","Experience","Education","Certifications","Projects","Awards","Achievements","Publications","Skills","Languages","Interests","References","Activities","Additional Information"]
    
        education_section = []
    
        in_education_section = False
        flag = False
    
        for line in lines:
            line = line.strip()
        
            if "Education" in line:
                in_education_section = True
                flag = True
            else:
                for header in headers:
                    if header in line and flag:
                        in_education_section = False
                        return education_section
        
            if in_education_section and line:
                education_section.append(line)
    
        return education_section
        # ... (Your existing extract_education function)
        # No need to modify this function

    def extract_skills(text):
        lines = text.split('\n')
        headers = ["Contact Information","Objective","Summary","Experience","Skills","Education","Certifications","Projects","Awards","Achievements","Publications","Languages","Interests","References","Activities","Additional Information"]
    
        skills_section = []
    
        in_skills_section = False
        flag = False
    
        for line in lines:
            line = line.strip()
        
            if "Skills" in line:
                in_skills_section = True
                flag = True
            else:
                for header in headers:
                    if header in line and flag:
                        in_skills_section = False
                        return skills_section
        
            if in_skills_section and line:
                skills_section.append(line)
    
        return skills_section
        # ... (Your existing extract_skills function)
        # No need to modify this function

    # Create a dictionary to store results for each resume with job ID as the key
    all_resume_details = {}

    # Iterate through all subdirectories and their files
    for root, dirs, files in os.walk(parent_folder_path):
        for pdf_file in files:
            if pdf_file.endswith(".pdf"):
                pdf_path = os.path.join(root, pdf_file)

                # Extract job ID from the PDF file name
                job_id = os.path.splitext(pdf_file)[0]

                # Extract text from the PDF using pdfplumber
                resume_text = extract_text_from_pdf(pdf_path)

                # Extract education and skills sections
                education = extract_education(resume_text)
                skills = extract_skills(resume_text)

                # Store the results in the dictionary using the job ID as the key
                all_resume_details[job_id] = {
                    "Education Section": education,
                    "Skills Section": skills,
                }

    return all_resume_details

# Define the path to the parent folder containing subfolders with resumes
parent_folder_path = "C:/Users/SATYESH/Downloads/resumedataset/data/data"

# Call the function to extract details from all resumes in the subfolders
all_resume_details = cv_details_extractor(parent_folder_path)

# Now, all_resume_details is a dictionary where each key is the job ID,
# and the corresponding value is a dictionary containing the education and skills sections.
# You can access the details for a specific resume like this:
# education_section = all_resume_details["10554236"]["Education Section"]
# skills_section = all_resume_details["10554236"]["Skills Section"]

# You can loop through all_resume_details to access details for all resumes.


KeyboardInterrupt: 

In [36]:
all_resume_details['49127329.pdf']

{'Education Section': ['Education',
  'MBA : Business Administration 2008 Seattle University - City , State',
  'Bachelors of Science : Industrial Engineering 6 2014 University of Washington - Industrial Engineering',
  'Project Management Certification - Stevens Institute -',
  'Accomplishments',
  'Has led and managed teams of Project Managers and Industrial Engineers Has worked with Employee Involvement/Engagement Teams to',
  'improve processes in the office and factory floor.',
  'Accelerated Improvement Workshop Certification Outgoing personality Honest and easy going Quick study and very dependable High',
  'sense of personal responsibility.'],
 'Skills Section': ['Skills',
  'Project planning and development',
  'Strategic planning Dedicated team player',
  'Lean manufacturing and design Procedure development',
  'Analytical Dependable',
  'Personable',
  'Work History',
  '737 Industrial Engineering Manager 01/2014 to Current',
  'Company Name – City , State',
  'Manage and 

In [14]:
education

['Education',
 'Computer Applications Specialist Certificate Program : 2008 Martinez Adult Education, Business Training Center ï¼\u200b City , State',
 'Skills',
 'accounts payables, accounts receivables, Accounts Payable, Accounts Receivable, administrative functions, trial balance, banking, budget, bi,',
 'closing, Computer Applications, Credit, clients, Customer Service, data entry, delivery, driving, email, insurance, inventory, ledger, Access, Excel,',
 'Outlook, PowerPoint, Word, mortgage loan, Enterprise, policies, QuickBooks, Sales, sales reports, telecommunications, phone, workflow,',
 'written']

In [15]:
skills

['Skills',
 'accounts payables, accounts receivables, Accounts Payable, Accounts Receivable, administrative functions, trial balance, banking, budget, bi,',
 'closing, Computer Applications, Credit, clients, Customer Service, data entry, delivery, driving, email, insurance, inventory, ledger, Access, Excel,',
 'Outlook, PowerPoint, Word, mortgage loan, Enterprise, policies, QuickBooks, Sales, sales reports, telecommunications, phone, workflow,',
 'written']

In [22]:
pip install transformers torch scikit-learn

Note: you may need to restart the kernel to use updated packages.


In [16]:
from transformers import DistilBertTokenizer, DistilBertModel
import torch
import pandas as pd
from sklearn.metrics.pairwise import cosine_similarity

# Load the DistilBERT tokenizer and model
tokenizer = DistilBertTokenizer.from_pretrained("distilbert-base-uncased")
model = DistilBertModel.from_pretrained("distilbert-base-uncased")

# Create a list to store CVs
cvs = []
current_cv = []

# Loop through the lines in education and skills
for line in education + skills:
    if line.startswith("Education:") or line.startswith("Skills:"):
        # If a new section begins, save the previous CV and start a new one
        if current_cv:
            cvs.append("\n".join(current_cv))
            current_cv = []
    current_cv.append(line)

# Add the last CV entry
if current_cv:
    cvs.append("\n".join(current_cv))

# Tokenize and embed CV details and job descriptions
cv_embeddings = []
job_description_embeddings = []

# Loop through each CV
for cv_text in cvs:
    inputs = tokenizer(cv_text, return_tensors="pt", padding=True, truncation=True)
    with torch.no_grad():
        outputs = model(**inputs)
    embeddings = torch.mean(outputs.last_hidden_state, dim=1)
    cv_embeddings.append(embeddings[0].numpy())  # Reshape to 2D array

# Tokenize and embed job descriptions
job_description_texts = job_descriptions.tolist()
for job_desc_text in job_description_texts:
    inputs = tokenizer(job_desc_text, return_tensors="pt", padding=True, truncation=True)
    with torch.no_grad():
        outputs = model(**inputs)
    embeddings = torch.mean(outputs.last_hidden_state, dim=1)
    job_description_embeddings.append(embeddings[0].numpy())  # Reshape to 2D array

# Calculate cosine similarity
similarity_scores = []

for jd_embedding in job_description_embeddings:
    scores = cosine_similarity([jd_embedding], cv_embeddings)  # Compute similarity for a single job description
    similarity_scores.append(scores[0])  # Append the result

# Now, similarity_scores will contain cosine similarity scores between each job description and all CVs.


In [17]:
similarity_scores

[array([0.7924509], dtype=float32),
 array([0.7388951], dtype=float32),
 array([0.8074971], dtype=float32),
 array([0.8049223], dtype=float32),
 array([0.8090556], dtype=float32),
 array([0.758705], dtype=float32),
 array([0.80254054], dtype=float32),
 array([0.8144622], dtype=float32),
 array([0.80630416], dtype=float32),
 array([0.804352], dtype=float32)]

In [18]:
current_cv

['Education',
 'Computer Applications Specialist Certificate Program : 2008 Martinez Adult Education, Business Training Center ï¼\u200b City , State',
 'Skills',
 'accounts payables, accounts receivables, Accounts Payable, Accounts Receivable, administrative functions, trial balance, banking, budget, bi,',
 'closing, Computer Applications, Credit, clients, Customer Service, data entry, delivery, driving, email, insurance, inventory, ledger, Access, Excel,',
 'Outlook, PowerPoint, Word, mortgage loan, Enterprise, policies, QuickBooks, Sales, sales reports, telecommunications, phone, workflow,',
 'written',
 'Skills',
 'accounts payables, accounts receivables, Accounts Payable, Accounts Receivable, administrative functions, trial balance, banking, budget, bi,',
 'closing, Computer Applications, Credit, clients, Customer Service, data entry, delivery, driving, email, insurance, inventory, ledger, Access, Excel,',
 'Outlook, PowerPoint, Word, mortgage loan, Enterprise, policies, QuickBooks

In [19]:
import os
import pandas as pd
import PyPDF2

# Define the paths to your files and folder
pdf_folder_path = "C:/Users/SATYESH/Downloads/resumedataset/data/data/HR"
csv_file_path = "C:/Users/SATYESH/Downloads/resumedataset/Resume/Resume.csv"

# Step 1: Extract the names of PDF files from the folder
pdf_files = [file for file in os.listdir(pdf_folder_path) if file.endswith(".pdf")]

# Step 2: Read the CSV file into a DataFrame
df = pd.read_csv(csv_file_path)

# Step 3: Initialize an empty list to store job categories
job_categories = []

# Step 4: Iterate through the PDF files and extract job IDs
for pdf_file in pdf_files:
    job_id = os.path.splitext(pdf_file)[0]  # Extract the job ID from the PDF filename
    job_id = int(job_id)  # Convert the job ID to an integer
    
    # Step 5: Find the corresponding job category in the DataFrame
    category = df[df['ID'] == job_id]['Category'].values[0]
    job_categories.append((job_id, category))

# Now, job_categories contains tuples with job IDs and their corresponding categories
# You can use this list for further processing
print(job_categories)


[(10399912, 'HR'), (10694288, 'HR'), (11480899, 'HR'), (11592605, 'HR'), (11698189, 'HR'), (11763983, 'HR'), (11847784, 'HR'), (12786012, 'HR'), (13376919, 'HR'), (13520837, 'HR'), (13879043, 'HR'), (14225422, 'HR'), (14256329, 'HR'), (14640322, 'HR'), (14886205, 'HR'), (15041689, 'HR'), (15375009, 'HR'), (15575117, 'HR'), (15576950, 'HR'), (16852973, 'HR'), (16861758, 'HR'), (16877897, 'HR'), (17150707, 'HR'), (17412079, 'HR'), (17422560, 'HR'), (17812897, 'HR'), (17855844, 'HR'), (18084150, 'HR'), (18155310, 'HR'), (18297650, 'HR'), (18316239, 'HR'), (18334783, 'HR'), (18422164, 'HR'), (18557164, 'HR'), (18731098, 'HR'), (18827609, 'HR'), (19179079, 'HR'), (19336728, 'HR'), (19616406, 'HR'), (19717385, 'HR'), (19867922, 'HR'), (20417897, 'HR'), (20806155, 'HR'), (20925036, 'HR'), (20993320, 'HR'), (21265194, 'HR'), (21830565, 'HR'), (22323967, 'HR'), (23155093, 'HR'), (23408537, 'HR'), (23510685, 'HR'), (23914451, 'HR'), (24184357, 'HR'), (24402267, 'HR'), (24508725, 'HR'), (25150191

In [20]:
def job_id_extractor(path_of_resume,save_path):# in save_path give the path of a specific category folder like for HR, give the path of HR folder
    import os
    import pandas as pd
    import PyPDF2

# Define the paths to your files and folder
    pdf_folder_path = path_of_resume
    csv_file_path = save_path

# Step 1: Extract the names of PDF files from the folder
    pdf_files = [file for file in os.listdir(pdf_folder_path) if file.endswith(".pdf")]

# Step 2: Read the CSV file into a DataFrame
    df = pd.read_csv(csv_file_path)

# Step 3: Initialize an empty list to store job categories
    job_categories = []

# Step 4: Iterate through the PDF files and extract job IDs
    for pdf_file in pdf_files:
        job_id = os.path.splitext(pdf_file)[0]  # Extract the job ID from the PDF filename
        job_id = int(job_id)  # Convert the job ID to an integer
    
    # Step 5: Find the corresponding job category in the DataFrame
        category = df[df['ID'] == job_id]['Category'].values[0]
        job_categories.append((job_id, category))

# Now, job_categories contains tuples with job IDs and their corresponding categories
# You can use this list for further processing
    print(job_categories)


In [21]:
def job_id_extractor_all(path_to_resume,path_to_id):
    
    import os
    import pandas as pd

# Define the path to the parent folder containing 24 subfolders with resumes
    parent_folder_path = path_to_resume

# Initialize an empty list to store job categories
    all_job_categories = []

# Define the path to the CSV file
    csv_file_path = path_to_id

# Read the CSV file into a DataFrame
    df = pd.read_csv(csv_file_path)

# Function to extract job ID and category from a PDF file
    def extract_job_info(pdf_file_path):
        job_id = os.path.splitext(os.path.basename(pdf_file_path))[0]  # Extract the job ID from the PDF filename
        job_id = int(job_id)  # Convert the job ID to an integer
        category = df[df['ID'] == job_id]['Category'].values[0]  # Find the corresponding job category
        return job_id, category

# Iterate through all subdirectories and their files
    for root, dirs, files in os.walk(parent_folder_path):
        for pdf_file in files:
            if pdf_file.endswith(".pdf"):
                pdf_path = os.path.join(root, pdf_file)

            # Extract job ID and category
                job_id, category = extract_job_info(pdf_path)

            # Append to the list of job categories
                all_job_categories.append((job_id, category))

# Now, all_job_categories contains tuples with job IDs and their corresponding categories
# for all resumes in the 24 subfolders.
    print(all_job_categories)


In [22]:
job_id_extractor_all('C:/Users/SATYESH/Downloads/resumedataset/data/data',"C:/Users/SATYESH/Downloads/resumedataset/Resume/Resume.csv")

[(10554236, 'ACCOUNTANT'), (10674770, 'ACCOUNTANT'), (11163645, 'ACCOUNTANT'), (11759079, 'ACCOUNTANT'), (12065211, 'ACCOUNTANT'), (12202337, 'ACCOUNTANT'), (12338274, 'ACCOUNTANT'), (12442909, 'ACCOUNTANT'), (12780508, 'ACCOUNTANT'), (12802330, 'ACCOUNTANT'), (13072019, 'ACCOUNTANT'), (13130984, 'ACCOUNTANT'), (13294301, 'ACCOUNTANT'), (13491889, 'ACCOUNTANT'), (13701259, 'ACCOUNTANT'), (14055988, 'ACCOUNTANT'), (14126433, 'ACCOUNTANT'), (14224370, 'ACCOUNTANT'), (14449423, 'ACCOUNTANT'), (14470533, 'ACCOUNTANT'), (14491649, 'ACCOUNTANT'), (14496667, 'ACCOUNTANT'), (15289348, 'ACCOUNTANT'), (15363277, 'ACCOUNTANT'), (15592167, 'ACCOUNTANT'), (15821633, 'ACCOUNTANT'), (15906625, 'ACCOUNTANT'), (16237710, 'ACCOUNTANT'), (17306905, 'ACCOUNTANT'), (17407184, 'ACCOUNTANT'), (17556527, 'ACCOUNTANT'), (18132924, 'ACCOUNTANT'), (18365791, 'ACCOUNTANT'), (18569929, 'ACCOUNTANT'), (18635654, 'ACCOUNTANT'), (18669563, 'ACCOUNTANT'), (19446337, 'ACCOUNTANT'), (19545827, 'ACCOUNTANT'), (20082776, 

In [23]:
pdf_files[0]

'10399912.pdf'

In [24]:
job_categories[0]

(10399912, 'HR')

In [ ]:
# Import required libraries
from transformers import DistilBertTokenizer, DistilBertModel
import torch
import pandas as pd
from sklearn.metrics.pairwise import cosine_similarity

# Load the DistilBERT tokenizer and model
tokenizer = DistilBertTokenizer.from_pretrained("distilbert-base-uncased")
model = DistilBertModel.from_pretrained("distilbert-base-uncased")

# Assuming you have all_resume_details as a dictionary with job IDs and CV details
# and job_descriptions as a Series of job descriptions

# Create a dictionary to store the top 5 CVs for each job description
top_cv_for_jobs = {}

# Tokenize and embed job descriptions
job_description_embeddings = []

job_description_texts = job_descriptions.tolist()
for job_desc_text in job_description_texts:
    inputs = tokenizer(job_desc_text, return_tensors="pt", padding=True, truncation=True)
    with torch.no_grad():
        outputs = model(**inputs)
    embeddings = torch.mean(outputs.last_hidden_state, dim=1)
    job_description_embeddings.append(embeddings[0].numpy())  # Reshape to 2D array

# Calculate cosine similarity for each job description
for index, jd_embedding in enumerate(job_description_embeddings):
    similarity_scores = []

    for job_id, cv_details in all_resume_details.items():
        # Combine education and skills details for each CV
        cv_text = "\n".join(cv_details.get("Education Section", []) + cv_details.get("Skills Section", []))

        # Tokenize and embed CV details
        inputs = tokenizer(cv_text, return_tensors="pt", padding=True, truncation=True)
        with torch.no_grad():
            outputs = model(**inputs)
        cv_embedding = torch.mean(outputs.last_hidden_state, dim=1)

        # Compute cosine similarity between job description and CV
        similarity = cosine_similarity([jd_embedding], [cv_embedding[0].numpy()])[0][0]

        similarity_scores.append((job_id, similarity))

    # Sort the CVs by similarity score in descending order
    similarity_scores.sort(key=lambda x: x[1], reverse=True)

    # Store the top 5 CVs for this job description
    top_cv_for_jobs[f"Job_{index + 1}"] = similarity_scores[:5]

# Print the top 5 CVs for each job description
for job, top_cvs in top_cv_for_jobs.items():
    print(f"Top 5 CVs for {job}:")
    for cv_id, score in top_cvs:
        print(f"Job ID: {cv_id}, Similarity Score: {score}")
    print()


In [35]:
# Import required libraries
from transformers import DistilBertTokenizer, DistilBertModel
import torch
import pandas as pd
from sklearn.metrics.pairwise import cosine_similarity

# Load the DistilBERT tokenizer and model
tokenizer = DistilBertTokenizer.from_pretrained("distilbert-base-uncased")
model = DistilBertModel.from_pretrained("distilbert-base-uncased")

# Assuming you have all_resume_details as a dictionary with job IDs and CV details
# and job_descriptions as a Series of job descriptions

# Select the first job description (index 0)
job_description = job_descriptions[0]

# Create a dictionary to store the top 5 CVs for the first job description
top_cv_for_first_job = {}

# Tokenize and embed the first job description
inputs = tokenizer(job_description, return_tensors="pt", padding=True, truncation=True)
with torch.no_grad():
    outputs = model(**inputs)
first_job_embedding = torch.mean(outputs.last_hidden_state, dim=1)

# ... (previous code)

# Calculate cosine similarity for the first job description
# ... (previous code)

# Calculate cosine similarity for the first job description
similarity_scores = []

for job_id, cv_details in all_resume_details.items():
    # Combine education and skills details for each CV
    cv_text = "\n".join(cv_details.get("Education Section", []) + cv_details.get("Skills Section", []))

    # Tokenize and embed CV details
    inputs = tokenizer(cv_text, return_tensors="pt", padding=True, truncation=True)
    with torch.no_grad():
        outputs = model(**inputs)
    cv_embedding = torch.mean(outputs.last_hidden_state, dim=1)

    # Compute cosine similarity between the first job description and CV
    similarity = cosine_similarity([first_job_embedding[0].numpy()], [cv_embedding[0].numpy()])[0][0]

    similarity_scores.append((job_id, similarity))

# ... (rest of the code)



# Sort the CVs by similarity score in descending order
similarity_scores.sort(key=lambda x: x[1], reverse=True)

# Store the top 5 CVs for the first job description
top_cv_for_first_job["Top 5 CVs for First Job Description"] = similarity_scores[:5]

# Print the top 5 CVs for the first job description
for job, top_cvs in top_cv_for_first_job.items():
    print(job)
    for cv_id, score in top_cvs:
        print(f"Job ID: {cv_id}, Similarity Score: {score}")


Top 5 CVs for First Job Description
Job ID: 49127329.pdf, Similarity Score: 0.9277364015579224
Job ID: 27152464.pdf, Similarity Score: 0.9264578223228455
Job ID: 17926546.pdf, Similarity Score: 0.9205546975135803
Job ID: 13149176.pdf, Similarity Score: 0.9122425317764282
Job ID: 27040860.pdf, Similarity Score: 0.9119260311126709
